project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Copyright 2023, ES" 
    right: 
      - icon: github
        href: https://github.com/ellasmpa
  title: "Ella's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: SternElla.pdf
        text: Resume
      - about.qmd
      - portfolio.qmd
      - walkthrough.qmd
      - textofpaper.qmd
      - newsstory.qmd
      - HWmapping.qmd
      - va_electionproject.qmd
      - newconceptwalkthrough.qmd
      - breakingnewsstory.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
