---
title: "Breaking News Story"
author: "Ella Louise Stern"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    self-contained: true
    toc: true
    toc-location: left
---

```{r}
## A new page featuring a sample “breaking news story” that is approximately 250 words and which features at least two pieces of information which are generated using inline R code within your Quarto document. In other words, an example would be “The election today resulted in ___ counties being won by the Republican candidate” where the __ is filled in on the fly by your inline R code. Note that to accomplish this your Quarto document will have to include the necessary R code chunks above to create the text or number objects you will insert into those spaces.Note that this is an example story you are writing - it can be based off of any dataset you choose to use, either one we’ve used previously or another you find. All elements needed to complete the code and the narrative must be part of your Quarto document, so whatever dataset you choose will need to be imported into the file at the top, etc, and then crunched appropriately to arrive at the number.To take a single value in a dataframe and convert it to a vector, you can use the pull() function if need be.
```

```{r}
library(tidyverse)
library(nycflights13) # <- make sure to install this package 
library(tidycensus)
library(janitor)
library(writexl)
library(here)
options(tigris_class = "sf")
```

```{r}
flights <- nycflights13::flights
```
```{r}
flights_leavingfromEWR <- flights %>% 
  filter(origin == "EWR") %>% 
  nrow()

flights_leavingfromEWR
```
There were `r flights_leavingfromEWR` departing EWR airport in 2013 in Newark, New Jersey. 

```{r}
longdelays_EWR <- flights
flights %>% 
  filter(origin == "EWR") %>% 
  filter(dep_delay < 4) %>% 
  nrow()

120835/73189

longdelays_JFK <- flights %>% 
  filter(origin == "JFK") %>% 
  filter(dep_delay < 4) %>% 
  nrow()

average_2013_flightdelay <- flights %>% 
  summarize(mean(dep_delay, na.rm = TRUE))

```
On average, flights in 2013 were delayed by `r average_2013_flightdelay` minutes.
```{r}
average_delays_EWR <- flights %>% 
  filter(origin == "EWR") %>% 
  summarize(mean(dep_delay, na.rm = TRUE))

average_delays_EWR
```
On average, flights departing Newark were delayed by `r average_delays_EWR` minutes.

