---
title: "News Story: Cultural Reporting"
---

*When I took Cultural Reporting with Jesse Holland, he challenged us to cover a community that we were not a part of for the whole semester; I decided to report on the disabled community at GW. The class taught me the importance of listening, advocating and challenging your preconceived notions. Below is the op-ed I wrote for the class arguing for increased accessibility on GW's campus. I spoke with members of the disabled community to learn more about their experiences with accessibility on campus, as well as GW administrators to understand what the school is doing to improve the quality of life for students with disabilities.*

------------------------------------------------------------------------

Nora Hoffman is a junior at George Washington University studying political science and english. She is hard of hearing. To accommodate her disability, GW provides live captioning done by a third party individual in her classes. The person doing live captioning is known as a communications access real-time translation, CART, provider.

The Friday before the start of the semester, Hoffman received an email from Disability Support Services alerting her that her captioner would be online for the entire semester. However, the technology needed for the CART provider to perform services online was not readily available.

According to Hoffman, a mic and receiver are also necessary for the CART provider to caption virtually --- it was not until 6 weeks into the semester that those tools were provided.

Hoffman replied to the email telling students the service would be online and asked why they hadn't heard this earlier.

Dr. Maggie Butler, the Director Disability Support Services/Office of Diversity, Equity, and Community Engagement, called her on the phone in an attempt to explain the situation. Hoffman, who is hard of hearing, can not take phone calls.

Hoffman said that this action was a "disconnect" on behalf of DSS.

"I just wish they would prioritize disabled students and accessibility more," Hoffman said.

When The George Washington University went online in March 2020, the administration quickly had to make adaptations and accommodations for "virtual learning." The university remained operational entirely online for nearly two years. Throughout the period of virtual learning, accommodations were quickly made for the sake of both the physical and mental well-being of students at the university. These accommodations contributed to the wellbeing and academic success of students given the ongoing crisis of the Covid-19 pandemic.

Many of these accommodations have remained or been adapted to in-person learning as the university came back in the fall of 2021. However, there are many students who have disabilities, both visible and invisible, that have needed similar accommodations well before March 2020.

It is imperative that the accommodations implemented as a result of the pandemic are maintained and supported despite the crisis no longer being as immediate.

In the past year, virtual learning accommodations have benefited the entire student population, demonstrating that accessibility improves everyone's collective well-being. Accessibility for students with disabilities should not be implemented only when it assists the able-bodied majority on campus. It is too late for the administration to correct these wrongs in making appropriate accommodations for those who needed it prior to the pandemic; however, it is of the utmost importance that they continue making accessibility a priority as they have demonstrated in the past year. Furthermore, this is an opportunity for the university to expand accessibility on campus both inside and outside the classroom for those with physical or other disabilities.

Accommodations such as having lecture slides posted to Blackboard was once seen as too much to ask for by students who faced physical limitations to being in the classroom. Now, GW requires professors to record and post lectures in case a sick student cannot come to class - even if "sick" is just a mild cold.

Shira Strongin is a senior at George Washington. She started school in the fall of 2017, but had to medically withdraw when she was unable to attend classes in person as a result of her chronic illness.

When she started to miss classes her freshman year as a result of her illness, she said the administration at GW was unwilling to allow her professors to record lectures or send her class material such as lecture powerpoints. Those are both standard practices now.

"When I was asking for these my freshmen year, none of this \[the pandemic\] had happened," said Strongin. "They \[the administration\] said that they couldn't and there was no precedent for it. And they were right about precedent, but they weren't right about couldn't. So now there's no excuse."

Strongin said it is deeply frustrating to think back on all the excuses they gave to her when she was struggling.

"There clearly were solutions, they just weren't willing." said Strongin.

Many accommodations given the pandemic's impact have carried over to in-person learning. Professors are regularly recording lectures and uploading recordings to Blackboard sites. This sort of standard-practice accommodation was not offered to those with disabilities who needed it before. Students and professors are also now required to wear masks to every class and in university buildings. More people wearing masks means less illness overall, especially during "sick seasons." For students with compromised immune systems, this adaptation allows them to feel more comfortable in classrooms. These contrasts begs the question of why accessibility only becomes relevant when it means accessibility for abled-bodied individuals.

Before the shift in culture as a result of the pandemic, it was commonplace for students to present evidence such as a doctor's note explaining why they had to miss class. This sort of behavior may be uncomfortable for students and also singles out those with disabilities - specifically those that they may not be particularly visible. Now, professors are much more accommodating toward students who feel sick to any degree. It has been common practice to skip class for something mild as a sore throat should so as to not put the entire class at risk for Covid-19.

When Covid-19 sent students home abruptly in March 2020, the university granted a pass/no pass option with no limit on how many classes it could be applied to. Therefore, a student could take any class pass/no pass and had until the end of the grading period to decide. In the following academic year, GW maintained the policy but it was only applicable for one class. A pass/no pass meant that the grade would have no bearing on a student's grade point average \[GPA\]. This accommodation helped students who may have been dealing with outside emotional stressors of being at home during the pandemic. It is naive of the university to think that now that classes are back in person, outside factors that may have made a student more inclined to take a class pass/no pass are suddenly non-existent. Therefore, the policy should still remain.

The change in culture and the adaption of many accommodations both through virtual learning and as the university has returned to in person learning is a result of the pandemic. Nonetheless, their ability to implement such accommodations for nearly 11,000 undergraduates makes it clear that they could have done so for the smaller, minority population of students with disabilities who would have benefited immensely from the expanded levels of accessibility. Their inability to do so is a reflection of systemic and institutional biases against students and people with disabilities. GW now has an opportunity to do better, and they should keep these accommodations in place and continue providing for students, both able-bodied and with disabilities, so as to provide the most accessible means of education for all individuals.
