---
title: "Policy Brief"
---

```{r}


```

*In spring 2021, I took state and urban policy problems with Professor Betz. The class explored policy issues in state and local governments. We explored topics such as infrastructure, budget allocation, and poverty. For our final, we had to write a policy brief to a local official from our home state urging a particular piece of legislation be passed. I wrote my brief encouraging my state senator to pass a bill that would require comprehensive sex education be taught in all New York public schools. You can read more about my research into how comprehensive sex education can lower teen pregnancy rates, STI infections among teens and promote positive health outcomes for young people in New York. I've included my statement of purpose and recommendation to my state senator.*

------------------------------------------------------------------------

**Title:** Implementing Comprehensive Sex Education in Public Schools for New York Senator Alessandra Biaggi, District 34

**Policymaker:** Senator Alessandra Biaggi of District 34 in New York.

**Statement of the Issue:**

Comprehensive sex education yields positive sexual health outcomes such as lower rates of teen pregnancy and sexually transmitted infections among adolescents. Comprehensive sex education is unlike the pro-abstinence curriculum that is widely implemented in schools across America. Studies have shown that sex education that emphasizes solely abstinence is statistically ineffective.  

New York's current sexual education curriculum is not effective at yielding positive sexual health outcomes, making the issue of comprehensive sex education apparent and urgent. New York has above the national average rates of teen pregnancy and abortion. Of the STI cases in New York State, adolescents aged 15-19 makeup half.  Assembly Bill 1904, which had a duplicate bill in the Senate, sought to "require the commissioner to establish a comprehensive sex education curriculum to be taught in grades 1-12," and failed this past year. The events of this past year, however, underscore the need for the issue of comprehensive sex education to be raised.  For example, since many states issued statewide lockdowns, people were forced into isolation and were sometimes confined to unhealthy living conditions including residing with abusers. Studies have found a drastic increase in reports of domestic abuse and intimate partner violence.  

Enacting legislation to improve sexual education curriculum would have far-reaching positive effects on the general well-being of marginalized adolescent communities that make up District 34, in particular. Data suggests that kids in these schools would greatly benefit from a diverse, culturally sensitive, comprehensive sexual education curriculum.  The lack of comprehensive sex education in schools directly correlates to students' negative sexual health and developmental wellbeing. Comprehensive sex education yields results that foster tangible positive outcomes for students such as better grades and test results. Research on well rounded education on issues such as contraceptive use, sexuality, and healthy relationships has proven to reduce risky behavior by adolescents and yield positive health outcomes in students. There is an urgent need to implement comprehensive sex education curriculum in public schools across New York state's 34th district.

**Recommendation**

Comprehensive sex education in schools across New York's 34th district would include education on healthy relationships, promote sexual wellbeing education and be responsive to the needs of students of different backgrounds. To effectively mitigate negative sexual health outcome among adolescents in New York State it is imperative that a comprehensive sex education curriculum is mandated in the public schools. Schools should not have the option to teach sex education and it should therefore have a comprehensive curriculum that follows the guidelines of institutions whose standards are grounded in research and data. The California's model uses curriculum written by different organizations such as Positive Prevention Plus. This proposed policy suggests that the best method for New York's implementation would be to follow the curriculum set forth by SIECUS' National Sex Education Standards (Second Edition). Requiring this curriculum from 6th through 12th grade, as done similarly in California, is the best method of implementation as well to bypass potential political confrontation on the matter as well as yield the most positive sexual health outcome by targeting a particularly vulnerable age demographic. 

To achieve the most equitable implementation, there should be a piece of this proposed policy which allocates funds specifically for low-income schools and marginalized communities in district 34, as modeled by the Colorado plan. This method ensures that communities which face disproportionate rates of negative health outcomes such as teen pregnancy get the education on preventative measures and consequential resources.

To be most successful in the given moment, supplementing curriculum with resources through online sources such as AMAZE is a viable option for this proposed policy. As the implementation could require extended time for teacher training and designation of funds for specific resources needed for a comprehensive sex education, utilizing these free resources is technically feasible and most timely. The result of this proposed policy will be tremendous for students in Senator Biaggi's district 34. It is of the utmost importance that students feel uplifted, valued, and empowered to make decisions about their sexual health, personal identity, and interpersonal relationships. By implementing a policy that provides the tools to empower such students it is without question that negative health outcomes currently plaguing New York State's youth will decline steadily. 

\
