---
title: "Virginia Election Project"
author: "Ella"
execute:
  echo: true
format:
  html:
    self-contained: true
    code-tools: true
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}


library(tidyverse)
library(janitor)
library(kableExtra)
library(here)
options(scipen = 999)
options(stringsAsFactors = FALSE)
library(tidyverse) 
library(janitor) 
library(readxl) 
library(scales)
library(lubridate)
library(ggthemes)
library(esquisse)


#load saved joined data file from previous script
joined_vacomparison <- readRDS(here("processed_data", "joined_vacomparison.rds"))



```

# Comparing Virgnia Gov vs. Prez

This dataset compares the percentage of votes between the 2021 virginia governor's race and the 2020 presidential election. You may be asking - why are we comparing these two elections? The answer lies in the implications of gubernatorial elections to presidential elections in the United States.

```{r}

head(joined_vacomparison)


```

```{r}
joined_vacomparison %>% 
  mutate(bidenwins = biden > trump,
         mcauliffewins = mcauliffe > youngkin,
         trumppct_wins = trump_pct > biden_pct,
         younkinpct_wins = pct_youngkin > pct_mcauliffe
  )

## this shows the congruency between the democrats and republicans winning across the election cycles. when biden had the most votes, youngkin also had the most votes. this holds true when looking at percentage of votes won by the republicans in the 2020 Presidential election and the gubernatorial race
```

```{r}
pctyoungkintrump <- joined_vacomparison %>% 
  mutate(pct_youngkin - trump_pct)

pctyoungkintrump

```
```{r}
```

